# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# For tmuxinator
set-option -g automatic-rename off
set-option -g allow-rename off

set -g mouse on
#set -g default-terminal "tmux-256color"
set -g default-terminal "xterm-256color" # Or 'iterm2' if it works better for you
set -as terminal-features ",xterm-256color:RGB" # Enable true color features
#set-option -sa terminal-overrides "xterm*:Tc"

# Set prefix to Command+space
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Open panes in current directory
bind '-' split-window -v -c "#{pane_current_path}"
bind '|' split-window -h -c "#{pane_current_path}"

# Vim-style pane navigation
unbind h
unbind j
unbind k
unbind l

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resizing windows/panes
bind-key -r H resize-pane -L 5
bind-key -r J resize-pane -D 5
bind-key -r K resize-pane -U 5
bind-key -r L resize-pane -R 5

# Keybind to reload tmux config
bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'

# Theme
set-option -g @catppuccin_flavour macchiato
run '~/.config/tmux/plugins/catppuccin-extended/catppuccin.tmux'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
