# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# For tmuxinator
set-option -g automatic-rename off
set-option -g allow-rename off

set -g mouse on
#set -g default-terminal "tmux-256color"
set -g default-terminal "xterm-256color" # Or 'iterm2' if it works better for you
set -as terminal-features ",xterm-256color:RGB" # Enable true color features
#set-option -sa terminal-overrides "xterm*:Tc"

# Set prefix to Command+space
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Open panes in current directory
bind '-' split-window -v -c "#{pane_current_path}"
bind '|' split-window -h -c "#{pane_current_path}"

# Vim-style pane navigation
unbind h
unbind j
unbind k
unbind l

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resizing windows/panes
bind-key -r H resize-pane -L 5
bind-key -r J resize-pane -D 5
bind-key -r K resize-pane -U 5
bind-key -r L resize-pane -R 5

# Keybind to reload tmux config
bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'

# Configure the catppuccin plugin
set -g @catppuccin_flavor "macchiato"

# Show last 2 path segments instead of window title
set -g @catppuccin_window_text " #(echo '#{pane_current_path}' | rev | cut -d'/' -f-2 | rev)"
set -g @catppuccin_window_current_text " #(echo '#{pane_current_path}' | rev | cut -d'/' -f-2 | rev)"

# Load catppuccin
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
# For TPM, instead use `run ~/.tmux/plugins/tmux/catppuccin.tmux`

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""

set -g status-right "#{E:@catppuccin_status_application}"
#set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_user}"
set -ag status-right "#{E:@catppuccin_status_host}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
#set -agF status-right "#{E:@catppuccin_status_battery}"

#run ~/.config/tmux/plugins/tmux-plugins/tmux-cpu/cpu.tmux
#run ~/.config/tmux/plugins/tmux-plugins/tmux-battery/battery.tmux

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
